name: Build TouchLooper DEB

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: theos
          theos-src: https://github.com/theos/theos
          theos-sdks: https://github.com/theos/sdks
          theos-sdks-branch: master

      - name: Build TouchLooper
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make clean
          make package FINALPACKAGE=1

      - name: Show generated DEBs
        run: |
          find . -type f -name "*.deb" -print

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: TouchLooper-Sileo-DEB
          path: packages/*.deb
          if-no-files-found: error
